---
title: Christopher Chang
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  sections:
    title: Section
    output: false
  uploads:
    title: Uploads
    output: false
description: Cras justo odio, dapibus ac facilisis in, egestas eget quam.
baseurl: ''
url: ''
markdown: kramdown
theme: minima
exclude:
- Gemfile
- Gemfile.lock
sass:
  style: compressed
